name: 'Run aragonCLI'

on: ['push']

jobs:
 build:
  runs-on: 'ubuntu-latest'

  strategy:
   matrix:
    node-version: [12.x]

  steps:
   - uses: 'actions/checkout@v2'
   - name: 'Use Node.js ${{ matrix.node-version }}'
     uses: 'actions/setup-node@v1'
     with:
      node-version: '${{ matrix.node-version }}'
      TEST: '${{ secrets.TEST }}'

   - name: Setup aragonCLI signer
     run: node ./src/setupAragon.js
     env:
      TEST: ${{ secrets.TEST }}
